"""
Invoice v2 - Conversation States
"""
from enum import IntEnum


class InvoiceV2State(IntEnum):
    """Conversation states for Invoice v2"""
    SEARCH_USER = 1
    SELECT_USER = 2
    ITEM_MODE = 3
    SEARCH_STORE_ITEM = 4
    SELECT_STORE_ITEM = 5
    CUSTOM_ITEM_NAME = 6
    CUSTOM_ITEM_RATE = 7
    ITEM_QUANTITY = 8
    ITEM_DISCOUNT = 9
    ITEM_CONFIRM = 10
    SHIPPING = 11
    FINAL_REVIEW = 12
    SEND_INVOICE = 13
    INVOICE_MENU = 20
    MANAGE_MENU = 21
    SEARCH_INVOICES = 22
    SEARCH_RESULTS = 23
    VIEW_INVOICE = 24
    CONFIRM_DELETE = 25
    EDIT_INVOICE = 26
    EDIT_ITEM_SELECT = 27
    EDIT_ITEM_FIELD = 28
    EDIT_ITEM_VALUE = 29
    ADD_ITEM_NAME = 30
    ADD_ITEM_RATE = 31
    ADD_ITEM_QTY = 32
    ADD_ITEM_DISCOUNT = 33
    ADD_ITEM_GST = 34
